name: "Setup Poetry environment"
author: "Tobias Caliskan"
description: "This action can be used to install the Poetry package manager in the workflows."

# Specify the inputs that can / must be provided when using this action
inputs:
  python-version:
    required: false
    description: "The Python version to use"
    default: "3.9"

runs:
  using: "composite"
  steps:
    - uses: actions/setup-python@v2
      # The with section specifies, which variables to use in the respective step
      with:
        python-version: ${{inputs.python-version}}
    - name: Install Poetry
      run: curl -sSL https://install.python-poetry.org | python3 -
      shell: bash
    - name: Create the environment
      run: poetry install
      shell: bash
