name: Test

on:
  pull_request:
  push:
    branches:
      - "**"
      
jobs:
  pre-commit:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: ./.github/actions/setup_poetry_env
      - run: poetry run pre-commit run --all-files
      
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: ./.github/actions/setup_poetry_env
      - run: poetry run pytest
