name: Test

on:
  pull_request:
  push:
    branches:
      - "**"

jobs:
  pre-commit:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: ./.github/actions/setup_poetry_env
      - run: poetry run pre-commit run --all-files

  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: ./.github/actions/setup_poetry_env
      - run: poetry run pytest
        env:
          API_CONTACT_NAME: ${{ secrets.API_CONTACT_NAME }}
          API_CONTACT_MAIL: ${{ secrets.API_CONTACT_MAIL }}
          API_CONTACT_SITE: ${{ secrets.API_CONTACT_SITE }}
          POSTGRES_SERVER: ${{ secrets.POSTGRES_SERVER }}
          POSTGRES_USER: ${{ secrets.POSTGRES_USER }}
          POSTGRES_PW: ${{ secrets.POSTGRES_PW }}
          POSTGRES_DB: ${{ secrets.POSTGRES_DB }}
          ADMIN_USER: ${{ secrets.ADMIN_USER }}
          ADMIN_PW: ${{ secrets.ADMIN_PW }}
          JWT_SECRET_KEY: ${{ secrets.JWT_SECRET_KEY }}
          JWT_REFRESH_SECRET_KEY: ${{ secrets.JWT_REFRESH_SECRET_KEY }}
          ALGORITHM: ${{ secrets.ALGORITHM }}
          ACCESS_TOKEN_EXPIRE_MINUTES: ${{ secrets.ACCESS_TOKEN_EXPIRE_MINUTES }}
          REFRESH_TOKEN_EXPIRE_MINUTES: ${{ secrets.REFRESH_TOKEN_EXPIRE_MINUTES }}
          SENTRY_DSN: ${{ secrets.SENTRY_DSN }}
